### ISSUE TITLE
Implementation of useContext and useReducer hook, 123 of section-8

### ISSUE THREAD

**Issue by anjali-sumfactor** [anjali-sumfactor/Next.JS#2]

**Comment by prashantsumfactor** [comment]
**useContext :** 

React Context is a way to manage state globally. [ as we know useState works only within scope of code ] 
It can be used together with the "useState" Hook to share state between deeply nested[parent-child] components more easily than with useState alone.

Without useContext, we will need to pass the state as "props" through each nested component. This is called "prop drilling", and it is complex as compare useContext.

Refer link - [https://www.w3schools.com/react/react_usecontext.asp](url)

**useReducer :** 

The useReducer hook is used for complex state manipulations and state transitions
It allows for custom state logic with different action.
If you find yourself keeping track of multiple pieces of state that rely on complex logic, useReducer may be useful

Refer link - [https://www.w3schools.com/react/react_usereducer.asp](url)
